# Generated by Django 2.2.6 on 2019-10-21 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasSights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField()),
                ('jdname', models.CharField(max_length=250)),
                ('jdename', models.CharField(max_length=250)),
                ('city_id', models.IntegerField()),
                ('brief_en', models.TextField()),
                ('brief_cn', models.TextField()),
            ],
            options={
                'db_table': 'tas_sights',
            },
        ),
        migrations.CreateModel(
            name='TasSightsPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='sid')),
                ('country_id', models.IntegerField(verbose_name='国家id')),
                ('city_id', models.IntegerField(verbose_name='城市id')),
                ('pname', models.CharField(max_length=250, null=True, verbose_name='名字')),
                ('p_purpose', models.IntegerField(null=True, verbose_name='景点用途，1封面，2内容')),
                ('p_copyright', models.IntegerField(null=True, verbose_name='是否有版权')),
                ('p_recommend', models.IntegerField(null=True, verbose_name='是否推荐')),
                ('hashcode', models.CharField(max_length=50, null=True, verbose_name='哈希值')),
                ('SavePath', models.CharField(max_length=250, null=True, verbose_name='路径')),
                ('UploadDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
            ],
            options={
                'db_table': 'tas_sight_pic',
            },
        ),
    ]
