# Generated by Django 2.2.6 on 2019-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tassightspic',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='tassightspic',
            name='country_id',
        ),
        migrations.AddField(
            model_name='tassightspic',
            name='bucket_key',
            field=models.CharField(default=None, max_length=250, verbose_name='oss文件夹名称'),
        ),
    ]
