# Generated by Django 2.2.6 on 2019-10-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0002_auto_20191021_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tassightspic',
            old_name='SavePath',
            new_name='savePath',
        ),
        migrations.RenameField(
            model_name='tassightspic',
            old_name='UploadDate',
            new_name='uploadDate',
        ),
    ]
