# Generated by Django 2.2.6 on 2019-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0003_auto_20191021_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tassights',
            name='brief_cn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tassights',
            name='brief_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tassights',
            name='jdename',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tassights',
            name='jdname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
